[package]
name = "actix-test"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
tokio = { version = "1", feature = ["full"] }
openssl = { version = "0.10" }
serde = { version = "1.0", features = ["derive"] }
